package entropy:core

world program {
   // similar to `variant`, but no type payloads
  variant error {
    invalid-transaction-request(string),
    evaluation(string)
  }
  /// Contains signature request data that is used by the runtime. Passed into `wasmtime::Store` for state (or maybe `wasmtime::Linker`).
  export evaluate: func(config: initial-state) -> result<_, error>

  record initial-state {
    /// The preimage of the user's data under program evaulation (eg. RLP-encoded ETH transaction request).
    data: list<u8>,
    /// The substrate account Id of the caller
    signature-request-key: list<u8>
  }
}
