[package]
name = "search_json"
version = "0.12.0"
authors = ["Entropy Cryptography <engineering@entropy.xyz>"]
homepage = "https://entropy.xyz/"
license = "Apache-2.0"
repository = "https://github.com/entropyxyz/constraints"
edition = "2021"

[workspace]

[dependencies]
json = "0.12"
json-core = { path = "../../core" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", tag = "v0.18.0", default-features = false, features = [
  "std",
] }


# TODO copy the json project into the programs example and then resolve the deps via crates registry or
