---
name: "Check build"
on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print version
        run: cargo --version
      - name: Run check
        run: cargo install cargo-risczero && cargo risczero install && cargo check